# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos7"

  config.vm.define :aloe do |node|
    node.vm.hostname = "aloe"
    node.vm.network :private_network, ip: "192.168.33.11"
  end

  config.vm.define :canna do |node|
    node.vm.hostname = "canna"
    node.vm.network :private_network, ip: "192.168.33.12"
  end

end
